services:
  pg:
    image: postgres:18.4
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ghcr.io/rsoda/olimotracker:latest
    restart: always
    environment: ...
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pgdata:
